############################################################
#
# 配置server
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB

############################################################
#
# 配置shiro https://alexxiyang.github.io/shiro-redis/#configurable-options
#
############################################################
shiro:
  enabled: true
  web:
    enabled: true
  annotations:
    enabled: true
  sessionManager:
    deleteInvalidSessions: true
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: true
  userNativeSessionManager: false
  loginUrl: /login
  successUrl: /index
  unauthorizedUrl: /403

############################################################
#
# 配置thymeleaf https://docs.spring.io/spring-boot/docs/2.7.18/reference/htmlsingle/
#
############################################################
spring:
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  ############################################################
#
# 配置数据源信息
#
############################################################
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/ms?useUnicode=true&characterEncoding=UTF-8&autoReconnect&useSSL=false
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1
############################################################
#
# mybatis-plus 配置 https://baomidou.com/pages/56bac0/#%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE
#
############################################################
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页插件配置
#  mybatis-plus.configuration.plugins=
#  mybatis-plus.configuration.plugins.pagination.type=com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor
############################################################
#
# logback日志 配置
#
############################################################
logging:
  config: classpath:logback-spring.xml
############################################################
#
# 自定义 配置
#
############################################################
ms:
  redisConfig:
    address: redis://127.0.0.1:6379
    database: 0
    password: foobared
    host: 127.0.0.1:6379

