############################################################
#
# 配置server
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB
############################################################
#
# 配置thymeleaf
#
############################################################
spring:
  thymeleaf:
    cache: false
############################################################

###########################################################
  #配置jackjson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone:
      Asia/Shanghai  #GMT+8
###########################################################

#
# 配置数据源信息
#
############################################################
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/hntt?useUnicode=true&characterEncoding=UTF-8&autoReconnect&useSSL=false&autoReconnect=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1
############################################################
#
# redis 配置
#
############################################################
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    password: foobared
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-wait: 1000  #最大阻塞等待时间(负数没限制)
        max-idle: 8 #最大空闲连接
        min-idle: 0  #最小空闲连接
        time-between-eviction-runs: -1
############################################################
#
# mybatis-plus 配置
#
############################################################
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 分页插件配置
#  mybatis-plus.configuration.plugins=
#  mybatis-plus.configuration.plugins.pagination.type=com.baomidou.mybatisplus.extension.plugins.inner.PaginationInnerInterceptor
############################################################
#
# logback日志 配置
#
############################################################
logging:
  config: classpath:logback-spring.xml
############################################################
#
# 自定义 配置 redission
#
############################################################
ms:
  redisConfig:
    address: redis://127.0.0.1:6379
    database: 0
    password: foobared
###############################################################
knife4j:
  enable: true
  production: false
  setting:
    # 开启动态请求参数，true-开启，false-关闭
    enableDynamicParameter: true



